/**
 * Build script to generate config files from environment variables
 * This script runs during the build process to inject environment variables
 * into the client-side configuration files.
 */

const fs = require('fs');
const path = require('path');

// Load environment variables
// In Vercel, process.env is available; locally, we load from .env file
// Try to load .env file if environment variables are not already set
try {
  const envFile = fs.readFileSync(path.join(__dirname, '.env'), 'utf8');
  envFile.split('\n').forEach(line => {
    const trimmedLine = line.trim();
    // Skip comments and empty lines
    if (!trimmedLine || trimmedLine.startsWith('#')) return;
    
    const [key, ...valueParts] = trimmedLine.split('=');
    if (key && valueParts.length > 0) {
      const value = valueParts.join('=').trim();
      // Remove quotes if present
      const cleanValue = value.replace(/^["']|["']$/g, '');
      // Only set if not already in process.env (environment variables take precedence)
      if (!process.env[key.trim()]) {
        process.env[key.trim()] = cleanValue;
      }
    }
  });
} catch (error) {
  // .env file not found - this is okay if environment variables are set in system/Vercel
  if (process.env.NODE_ENV !== 'production') {
    console.warn('Warning: .env file not found. Make sure environment variables are set.');
  }
}

// Get environment variables with fallback to empty strings
const SUPABASE_URL = process.env.VITE_SUPABASE_URL || process.env.SUPABASE_URL || '';
const SUPABASE_ANON_KEY = process.env.VITE_SUPABASE_ANON_KEY || process.env.SUPABASE_ANON_KEY || '';
const INTERCOM_ACCESS_TOKEN = process.env.VITE_INTERCOM_ACCESS_TOKEN || process.env.INTERCOM_ACCESS_TOKEN || '';
const INTERCOM_APP_ID = process.env.VITE_INTERCOM_APP_ID || process.env.INTERCOM_APP_ID || '';

// Validate required environment variables
if (!SUPABASE_URL || !SUPABASE_ANON_KEY) {
  console.error('Error: SUPABASE_URL and SUPABASE_ANON_KEY are required');
  console.error('Please set them in your .env file or Vercel environment variables');
  process.exit(1);
}

// Warn if Intercom variables are missing (optional)
if (!INTERCOM_ACCESS_TOKEN || !INTERCOM_APP_ID) {
  console.warn('Warning: INTERCOM_ACCESS_TOKEN and/or INTERCOM_APP_ID are not set');
  console.warn('Intercom features may not work properly');
}

// Generate env-config.js (browser-compatible config from environment variables)
const envConfigContent = `/**
 * Environment Configuration
 * This file is auto-generated from environment variables
 * DO NOT EDIT THIS FILE MANUALLY - This file is generated by build-config.js
 */

window.env = {
  SUPABASE_URL: '${SUPABASE_URL}',
  SUPABASE_ANON_KEY: '${SUPABASE_ANON_KEY}',
  INTERCOM_ACCESS_TOKEN: '${INTERCOM_ACCESS_TOKEN}',
  INTERCOM_API_BASE_URL: 'https://api.intercom.io',
  INTERCOM_APP_ID: '${INTERCOM_APP_ID}'
};
`;

// Note: supabase-config.js and intercom-config.js are now source files
// that read from window.env. They are NOT generated by this script anymore.
// They should be committed to the repository and will read from env-config.js
// which is generated at build time.

// Write env-config.js file
const envConfigPath = path.join(__dirname, 'env-config.js');
fs.writeFileSync(envConfigPath, envConfigContent, 'utf8');

console.log('✓ Generated env-config.js from environment variables');

// Validate that required variables are set
const requiredVars = ['SUPABASE_URL', 'SUPABASE_ANON_KEY'];
const missingVars = requiredVars.filter(varName => {
  const value = varName === 'SUPABASE_URL' ? SUPABASE_URL : SUPABASE_ANON_KEY;
  return !value;
});

if (missingVars.length > 0) {
  console.warn(`⚠ Warning: Missing required environment variables: ${missingVars.join(', ')}`);
  console.warn('  Make sure to set these in your .env file or Vercel environment variables');
}

